
export const GET_HAIR_COOLORS = "GET_HAIR_COOLORS"
export const GET_HAIR_COOLORS_SUCCESS = "GET_HAIR_COOLORS_SUCCESS"
export const GET_HAIR_COOLORS_FAIL = "GET_HAIR_COOLORS_FAIL"

export const GET_HAIR_COOLOR_PROFILE = "GET_HAIR_COOLOR_PROFILE"
export const GET_HAIR_COOLOR_PROFILE_SUCCESS = "GET_HAIR_COOLOR_PROFILE_SUCCESS"
export const GET_HAIR_COOLOR_PROFILE_FAIL = "GET_HAIR_COOLOR_PROFILE_FAIL"

export const ADD_NEW_HAIR_COOLOR = "ADD_NEW_HAIR_COOLOR"
export const ADD_HAIR_COOLOR_SUCCESS = "ADD_HAIR_COOLOR_SUCCESS"
export const ADD_HAIR_COOLOR_FAIL = "ADD_HAIR_COOLOR_FAIL"

export const UPDATE_HAIR_COOLOR = "UPDATE_HAIR_COOLOR"
export const UPDATE_HAIR_COOLOR_SUCCESS = "UPDATE_HAIR_COOLOR_SUCCESS"
export const UPDATE_HAIR_COOLOR_FAIL = "UPDATE_HAIR_COOLOR_FAIL"


export const DELETE_HAIR_COOLOR = "DELETE_HAIR_COOLOR"
export const DELETE_HAIR_COOLOR_SUCCESS = "DELETE_HAIR_COOLOR_SUCCESS"
export const DELETE_HAIR_COOLOR_FAIL = "DELETE_HAIR_COOLOR_FAIL"
