
export const GET_ATTRIBUTES = "GET_ATTRIBUTES"
export const GET_ATTRIBUTES_SUCCESS = "GET_ATTRIBUTES_SUCCESS"
export const GET_ATTRIBUTES_FAIL = "GET_ATTRIBUTES_FAIL"

export const GET_ATTRIBUTE_PROFILE = "GET_ATTRIBUTE_PROFILE"
export const GET_ATTRIBUTE_PROFILE_SUCCESS = "GET_ATTRIBUTE_PROFILE_SUCCESS"
export const GET_ATTRIBUTE_PROFILE_FAIL = "GET_ATTRIBUTE_PROFILE_FAIL"

export const ADD_NEW_ATTRIBUTE = "ADD_NEW_ATTRIBUTE"
export const ADD_ATTRIBUTE_SUCCESS = "ADD_ATTRIBUTE_SUCCESS"
export const ADD_ATTRIBUTE_FAIL = "ADD_ATTRIBUTE_FAIL"

export const UPDATE_ATTRIBUTE = "UPDATE_ATTRIBUTE"
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS"
export const UPDATE_ATTRIBUTE_FAIL = "UPDATE_ATTRIBUTE_FAIL"


export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE"
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS"
export const DELETE_ATTRIBUTE_FAIL = "DELETE_ATTRIBUTE_FAIL"
