
export const GET_TRAIT_TYPES = "GET_TRAIT_TYPES"
export const GET_TRAIT_TYPES_SUCCESS = "GET_TRAIT_TYPES_SUCCESS"
export const GET_TRAIT_TYPES_FAIL = "GET_TRAIT_TYPES_FAIL"

export const GET_TRAIT_TYPE_PROFILE = "GET_TRAIT_TYPE_PROFILE"
export const GET_TRAIT_TYPE_PROFILE_SUCCESS = "GET_TRAIT_TYPE_PROFILE_SUCCESS"
export const GET_TRAIT_TYPE_PROFILE_FAIL = "GET_TRAIT_TYPE_PROFILE_FAIL"

export const ADD_NEW_TRAIT_TYPE = "ADD_NEW_TRAIT_TYPE"
export const ADD_TRAIT_TYPE_SUCCESS = "ADD_TRAIT_TYPE_SUCCESS"
export const ADD_TRAIT_TYPE_FAIL = "ADD_TRAIT_TYPE_FAIL"

export const UPDATE_TRAIT_TYPE = "UPDATE_TRAIT_TYPE"
export const UPDATE_TRAIT_TYPE_SUCCESS = "UPDATE_TRAIT_TYPE_SUCCESS"
export const UPDATE_TRAIT_TYPE_FAIL = "UPDATE_TRAIT_TYPE_FAIL"


export const DELETE_TRAIT_TYPE = "DELETE_TRAIT_TYPE"
export const DELETE_TRAIT_TYPE_SUCCESS = "DELETE_TRAIT_TYPE_SUCCESS"
export const DELETE_TRAIT_TYPE_FAIL = "DELETE_TRAIT_TYPE_FAIL"
