
export const GET_COLORS = "GET_COLORS"
export const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS"
export const GET_COLORS_FAIL = "GET_COLORS_FAIL"

export const GET_COLOR_PROFILE = "GET_COLOR_PROFILE"
export const GET_COLOR_PROFILE_SUCCESS = "GET_COLOR_PROFILE_SUCCESS"
export const GET_COLOR_PROFILE_FAIL = "GET_COLOR_PROFILE_FAIL"

export const ADD_NEW_COLOR = "ADD_NEW_COLOR"
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS"
export const ADD_COLOR_FAIL = "ADD_COLOR_FAIL"

export const UPDATE_COLOR = "UPDATE_COLOR"
export const UPDATE_COLOR_SUCCESS = "UPDATE_COLOR_SUCCESS"
export const UPDATE_COLOR_FAIL = "UPDATE_COLOR_FAIL"


export const DELETE_COLOR = "DELETE_COLOR"
export const DELETE_COLOR_SUCCESS = "DELETE_COLOR_SUCCESS"
export const DELETE_COLOR_FAIL = "DELETE_COLOR_FAIL"
